import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-slate-50 antialiased font-body">
        <div className="container mx-auto px-4 md:px-0">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
